"""The model lifecycle state model and its bounded start measurements.

Two comparisons, and the difference between them is one read. The cold/warm pair
reads the artifact end to end between its two starts, so the second one finds the
host's file cache warm. The restart pair reads nothing in between, so the only
thing that changed between its two starts is that a runtime stopped.
"""

from .core import (
    EXPECTED_RESULT_DIRECTORY,
    LIFECYCLE_PATH,
    MODEL_CACHE_DIRECTORY,
    CacheObservation,
    CacheRule,
    CacheState,
    CleanupResult,
    ComparisonResult,
    Environment,
    LifecycleRefused,
    LifecycleState,
    ModelLifecycle,
    ModelLifecycleError,
    ProbeOutcome,
    ProbeSample,
    RestartResult,
    StartObservation,
    StateRule,
    Transition,
    capture_environment,
    clean_results,
    compare_restart,
    compare_starts,
    load_lifecycle,
    observation_document,
    observe_cache,
    observe_start,
    read_restart_results,
    read_results,
    result_directory,
    summarize,
    summarize_restart,
    write_restart_results,
    write_results,
)

__all__ = [
    "EXPECTED_RESULT_DIRECTORY",
    "LIFECYCLE_PATH",
    "MODEL_CACHE_DIRECTORY",
    "CacheObservation",
    "CacheRule",
    "CacheState",
    "CleanupResult",
    "ComparisonResult",
    "Environment",
    "LifecycleRefused",
    "LifecycleState",
    "ModelLifecycle",
    "ModelLifecycleError",
    "ProbeOutcome",
    "ProbeSample",
    "RestartResult",
    "StartObservation",
    "StateRule",
    "Transition",
    "capture_environment",
    "clean_results",
    "compare_restart",
    "compare_starts",
    "load_lifecycle",
    "observation_document",
    "observe_cache",
    "observe_start",
    "read_restart_results",
    "read_results",
    "result_directory",
    "summarize",
    "summarize_restart",
    "write_restart_results",
    "write_results",
]
