"""Check and evaluate the committed correlation query record.

    python -m tools.telemetry_correlation
    python -m tools.telemetry_correlation --json
    python -m tools.telemetry_correlation --evaluate
    python -m tools.telemetry_correlation --evidence

The first two apply the query policy: every expression is parsed with the declared
PromQL subset and refused if it reads a series nothing produces, names a label
nothing carries or the catalog bars, joins on a key one side cannot have, or claims
an answer a signal nothing emits cannot give. Exit status is 0 when nothing is
refused and 1 when anything is, so the command is usable as a gate.

``--evaluate`` runs every accepted query against every committed scenario fixture and
prints what each one returned. ``--evidence`` prints the same thing as the evidence
document under ``docs/proof/telemetry/``; the suite regenerates it and fails if the
committed copy has drifted, which is how a record of what a query returned stays a
record rather than a memory.

The suite under ``tests/telemetry/test_telemetry_correlation.py`` is the
authoritative check and runs in the default lane. This entry point exists so that an
operator can apply the same rules to a query they are about to paste into a console.

**It reads files.** It contacts no cluster, starts no Prometheus, and evaluates
nothing against a store that has ever held a sample. A passing result says a query
would be well formed against the labels the chart's rendered scrape configuration
would attach, and says nothing about a query that was ever answered. See
docs/telemetry/telemetry-correlation-queries.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any

from .core import (
    FIXTURE_DIR,
    check_record,
    evaluate_scenario,
    load_fixture,
    load_query_record,
)

#: The heading of the committed evidence document. It is here rather than in the
#: document because the document is generated from this module and compared against
#: what it generates.
EVIDENCE_TITLE = "V1-S3-007-PR2 query evaluation — every published query, over every committed scenario"


def _evidence(record: dict[str, Any]) -> str:
    queries = record["queries"]
    by_id = {query["queryId"]: query for query in queries}
    lines = [
        f"# {EVIDENCE_TITLE}",
        "",
        "Generated by `python -m tools.telemetry_correlation --evidence` and compared",
        "against this file by `tests/telemetry/test_telemetry_correlation.py`. Editing it",
        "by hand makes that suite fail, which is the point: it is a record of what the",
        "queries returned, not a description of what somebody expected them to.",
        "",
        "**Evidence class `local-static`, and every store below is synthetic.** No",
        "Prometheus parsed, loaded, or evaluated any expression here. Every result was",
        "produced by the declared PromQL subset evaluator in",
        "[`tools/telemetry_correlation/evaluate.py`](../../../tools/telemetry_correlation/evaluate.py)",
        "over fixture series written by hand in",
        "[`tests/telemetry/fixtures/correlation/`](../../../tests/telemetry/fixtures/correlation/).",
        "Nothing was scraped and no endpoint was contacted by this evaluation: every",
        "series below is a fixture. A real collector has since been installed and",
        "queried on `docker-desktop`; that record is separate, and this one",
        "establishes nothing about it.",
        "",
        "A query absent from a scenario is a query the scenario's profile does not render.",
        "A query present with no rows returned an empty vector, which is a different",
        "answer and is written differently.",
        "",
        "## The queries",
        "",
        "Each expression is written once here and referred to by identifier below.",
        "",
    ]
    for query in queries:
        lines.append(f"### `{query['queryId']}` — {query['answerability']}")
        lines.append("")
        lines.append(f"> {query['question']}")
        lines.append("")
        if query["expr"] is None:
            lines.append(
                "No expression. There is no series to select: "
                + str(query["wouldRequire"])
                + " would be needed first."
            )
        else:
            lines.append("```promql")
            lines.append(str(query["expr"]))
            lines.append("```")
        lines.append("")

    lines.append("## The results")
    lines.append("")
    for scenario in record["scenarios"]:
        fixture = load_fixture(FIXTURE_DIR / f"{scenario['scenarioId']}.yaml")
        results = evaluate_scenario(fixture, queries)
        lines.append(f"### `{scenario['scenarioId']}` — {scenario['profile']} profile")
        lines.append("")
        lines.append(scenario["whatItShows"])
        lines.append("")
        for query_id in sorted(results):
            lines.append(f"#### `{query_id}`")
            lines.append("")
            if results[query_id]:
                lines.append("```")
                lines.extend(results[query_id])
                lines.append("```")
            else:
                lines.append("Empty. " + str(by_id[query_id]["emptyMeans"]))
            lines.append("")
        absent = sorted(
            query["queryId"] for query in queries if query["queryId"] not in results
        )
        lines.append(
            "Not evaluated in this scenario: "
            + ", ".join(f"`{query_id}`" for query_id in absent)
            + ". Each either has no expression to run or is not rendered under the "
            + f"{scenario['profile']} profile."
        )
        lines.append("")
    # rstrip, so that the last section does not leave a blank line at end of file:
    # `git diff --check` reports one, and then a reviewer has to think about it.
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tools.telemetry_correlation",
        description=(
            "Apply the correlation query policy to the committed query record, and "
            "evaluate the accepted queries against the committed scenario fixtures."
        ),
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--json", action="store_true", help="emit findings as JSON instead of text"
    )
    group.add_argument(
        "--evaluate",
        action="store_true",
        help="run every query against every scenario and print what it returned",
    )
    group.add_argument(
        "--evidence",
        action="store_true",
        help="print the same results as the committed evidence document",
    )
    arguments = parser.parse_args(argv)

    record = load_query_record()
    findings = check_record(record)

    if arguments.evidence:
        if findings:
            print(
                "REFUSED  the record does not satisfy the query policy; no evidence "
                "is generated from a record that was refused",
                file=sys.stderr,
            )
            return 1
        print(_evidence(record), end="")
        return 0

    if arguments.evaluate:
        if findings:
            print(
                "REFUSED  the record does not satisfy the query policy",
                file=sys.stderr,
            )
            return 1
        for scenario in record["scenarios"]:
            fixture = load_fixture(FIXTURE_DIR / f"{scenario['scenarioId']}.yaml")
            results = evaluate_scenario(fixture, record["queries"])
            print(f"== {scenario['scenarioId']} ({scenario['profile']})")
            for query_id in sorted(results):
                rows = results[query_id]
                if rows:
                    print(f"   {query_id}")
                    for row in rows:
                        print(f"       {row}")
                else:
                    print(f"   {query_id}  (empty)")
        return 0

    if arguments.json:
        print(
            json.dumps(
                {
                    "record": "docs/telemetry/telemetry-correlation-queries.v1alpha1.json",
                    "queries": len(record["queries"]),
                    "scenarios": len(record["scenarios"]),
                    "valid": not findings,
                    "findings": [finding.as_dict() for finding in findings],
                },
                indent=2,
                sort_keys=True,
            )
        )
    elif findings:
        print(
            f"REFUSED {len(record['queries'])} quer(ies)  ({len(findings)} finding(s))"
        )
        for finding in findings:
            print(f"        {finding}")
    else:
        print(
            f"ok      {len(record['queries'])} quer(ies) satisfy the correlation "
            "query policy"
        )

    return 1 if findings else 0


if __name__ == "__main__":  # pragma: no cover - exercised through the CLI
    sys.exit(main())
