"""Verify the Git desired-state tree, or regenerate one of its releases on purpose.

    python -m tools.gitops_desired_state --list
    python -m tools.gitops_desired_state --check
    python -m tools.gitops_desired_state --write KEY [KEY ...]

``--root DIRECTORY`` reads, and writes, a copy of the repository instead of this
checkout. The suite uses it to plant defects without touching the committed files.

``--list`` prints every desired-state release, its key, and the inputs it is
derived from.

``--check`` verifies the whole tree: that each release is at the path its binding
and contract derive, that each is byte for byte what its declared sources derive,
and that ``gitops/`` holds nothing else. Exit status is 0 when the tree breaks no
rule and 1 when it breaks one, so the command is usable as a gate. ``--check``
writes nothing and repairs nothing.

``--write`` is the only mode that touches a file. It regenerates each release it is
given by key, ``<binding name>/<workload>``, through the platform's writer. It
refuses a release whose declaration or path breaks a rule. Nothing is regenerated by
default. Read the ``--check`` output first, because regeneration replaces a hand
edit without asking.

**Every mode reads committed files only.** None contacts a cluster, a registry, a
network, or a model, and none runs Helm or Git. A regenerated release changes the
desired state only when a reviewed change that contains it is accepted.
See docs/environment/git-desired-state.md.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from tools.generated_release import (
    DeclaredRelease,
    RegenerationRefused,
    SourcesRefused,
)

from .core import (
    DESIRED_STATE_RELEASES,
    REPO_ROOT,
    RULES,
    WriteRefused,
    desired_state_release,
    regenerate_release,
    release_key,
    verify_tree,
)


def _list() -> int:
    for declared in DESIRED_STATE_RELEASES:
        print(release_key(declared))
        print(f"  directory                   {declared.directory}")
        print(f"  contract                    {declared.contract}")
        for path in declared.bindings:
            print(f"  binding                     {path}")
        print(f"  binding name                {declared.binding_name}")
        print(f"  platform defaults           {declared.platform_defaults} (api)")
        print(f"  platform-defaults revision  {declared.platform_defaults_revision}")
        print(f"  renderer revision           {declared.renderer_revision}")
    return 0


def _check(root: Path) -> int:
    findings = verify_tree(root)
    if not findings:
        for declared in DESIRED_STATE_RELEASES:
            print(f"OK       {release_key(declared)}: {declared.directory}")
        print("OK       the tree holds the declared releases and nothing else")
        return 0
    statements = {rule.rule_id: rule.statement for rule in RULES}
    for finding in findings:
        print(f"REFUSED  {finding.rule_id}")
        print(f"         {finding.subject}: {finding.detail}")
        print(f"         {statements[finding.rule_id]}")
        for line in finding.diff:
            print(f"         {line}")
    print(f"{len(findings)} findings in the desired-state tree")
    return 1


def _write(selected: Sequence[DeclaredRelease], root: Path) -> int:
    status = 0
    for declared in selected:
        key = release_key(declared)
        try:
            written = regenerate_release(declared, root)
        except SourcesRefused as refused:
            print(f"REFUSED  {key}: nothing was written: {refused.reason}")
            status = 1
            continue
        except (WriteRefused, RegenerationRefused) as refused:
            print(f"REFUSED  {key}: nothing was written")
            for finding in refused.findings:
                print(
                    f"         {finding.rule_id}  {finding.subject}: {finding.detail}"
                )
            status = 1
            continue
        except OSError as error:
            print(f"FAILED   {key}: {type(error).__name__}: {error}")
            print(
                "         the release directory may be absent; run --write again, "
                "or restore it from Git"
            )
            status = 1
            continue
        if written:
            print(f"WROTE    {declared.directory}")
        else:
            print(f"UNCHANGED {declared.directory}")
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tools.gitops_desired_state",
        description=(
            "Verify the Git desired-state tree against its declared releases, or "
            "regenerate a release named by key."
        ),
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--list",
        action="store_true",
        help="print every desired-state release and its inputs",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="verify the whole tree; writes nothing",
    )
    group.add_argument(
        "--write",
        action="store_true",
        help="regenerate the releases named by key",
    )
    parser.add_argument(
        "keys", nargs="*", metavar="KEY", help="<binding name>/<workload>"
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="the repository copy to read and write (default: this checkout)",
    )
    arguments = parser.parse_args(argv)

    if arguments.list or arguments.check:
        if arguments.keys:
            parser.error("--list and --check take no release key")
        return _list() if arguments.list else _check(arguments.root)
    if not arguments.keys:
        parser.error("--write regenerates only the releases it is given by key")
    selected = []
    for key in arguments.keys:
        try:
            selected.append(desired_state_release(key))
        except KeyError:
            known = ", ".join(release_key(d) for d in DESIRED_STATE_RELEASES)
            parser.error(
                f"no desired-state release has the key {key!r}; known: {known}"
            )
    return _write(selected, arguments.root)


if __name__ == "__main__":  # pragma: no cover - exercised as a subprocess
    sys.exit(main())
