"""The V1 evidence index: one entry per evidence record, bound to its files by hash.

The index is generated from
[the claim and evidence register](../../docs/testing/claim-evidence-matrix.v1alpha2.json),
[the normalization ledger](../../docs/proof/testing/v1-s5-006-pr1-normalization.v1alpha1.json),
[the completeness ledger](../../docs/proof/testing/v1-s5-006-pr2-completeness.v1alpha1.json),
[the closure ledger](../../docs/proof/testing/v1-s5-013-pr1-closure.v1alpha1.json),
[the publication ledger](../../docs/proof/testing/v1-s5-013-pr2-publication.v1alpha1.json),
[the post-release ledger](../../docs/proof/testing/v1-s5-009-pr1-post-release.v1alpha1.json),
and [the claim reconciliation ledger](../../docs/proof/testing/v2-s2-001-pr2-claim-reconciliation.v1alpha1.json),
and it says nothing they do not. See
[the index's own page](../../docs/proof/v1-evidence-index.md).
"""

from __future__ import annotations

from .core import (
    BLOCKER_CLOSURES,
    CLAIM_RECONCILIATION_PATH,
    CLOSURE_PATH,
    CODE_IDENTITIES,
    CODE_REVISION_RELATIONS,
    COMPLETENESS_PATH,
    DISPOSITIONS,
    E01_STATIC_PROOF_PATH,
    FINAL_STATES,
    FREEZE_DECISIONS,
    INDEX_CONTRACT_VERSION,
    INDEX_PATH,
    LEDGER_PATH,
    LEDGER_PATHS,
    LEVEL_ORDER,
    POST_RELEASE_LEDGER_PATHS,
    POST_RELEASE_PATH,
    PUBLICATION_PATH,
    RELEASED_DIGESTS,
    RELEASED_LEDGER_PATHS,
    TEXT_SUFFIXES,
    apply_register_changes,
    build_index,
    content_sha256,
    entry_sha256,
    evidence_freeze,
    evidence_set_sha256,
    git_blob_id,
    load_index,
    load_ledger,
    load_ledgers,
    merged_identities,
    open_blockers,
    pack_sources,
    recorded_date,
    release_gate,
    released_pack,
    released_register,
    render_index,
    render_register,
    restore_migrated_register,
    states_authorisation,
)

__all__ = [
    "BLOCKER_CLOSURES",
    "CLAIM_RECONCILIATION_PATH",
    "CLOSURE_PATH",
    "CODE_IDENTITIES",
    "CODE_REVISION_RELATIONS",
    "COMPLETENESS_PATH",
    "DISPOSITIONS",
    "E01_STATIC_PROOF_PATH",
    "FINAL_STATES",
    "FREEZE_DECISIONS",
    "INDEX_CONTRACT_VERSION",
    "INDEX_PATH",
    "LEDGER_PATH",
    "LEDGER_PATHS",
    "LEVEL_ORDER",
    "POST_RELEASE_LEDGER_PATHS",
    "POST_RELEASE_PATH",
    "PUBLICATION_PATH",
    "RELEASED_DIGESTS",
    "RELEASED_LEDGER_PATHS",
    "TEXT_SUFFIXES",
    "apply_register_changes",
    "build_index",
    "content_sha256",
    "entry_sha256",
    "evidence_freeze",
    "evidence_set_sha256",
    "git_blob_id",
    "load_index",
    "load_ledger",
    "load_ledgers",
    "merged_identities",
    "open_blockers",
    "pack_sources",
    "recorded_date",
    "release_gate",
    "released_pack",
    "released_register",
    "render_index",
    "render_register",
    "restore_migrated_register",
    "states_authorisation",
]
