"""Verify the committed generated releases, or regenerate one on purpose.

    python -m tools.generated_release --list
    python -m tools.generated_release --check [NAME ...]
    python -m tools.generated_release --write NAME [NAME ...]

``--root DIRECTORY`` reads, and writes, a copy of the repository instead of this
checkout. The suite uses it to plant drift without touching the committed files.

``--list`` prints every declared release and the inputs it is derived from.

``--check`` derives each release again from its declared inputs and compares both
committed files with the derived ones, byte for byte. Exit status is 0 when every
release checked is what its sources derive and 1 when any is not, so the command is
usable as a gate. A drifted release is reported with the rule it breaks, the release
fields that differ and what each difference means, and a unified diff from the
committed file to the derived one. ``--check`` writes nothing and repairs nothing.

``--write`` is the only mode that touches a file. It regenerates each named release
in place, through the platform's writer, and refuses a directory that holds anything
the platform did not write. A release must be named: nothing is regenerated by
default. Read the ``--check`` diff first, because regeneration replaces a hand edit
without asking.

**Every mode reads committed files only.** None contacts a cluster, a registry, a
network, or a model, and none runs Helm. See docs/domain/helm-values-renderer.md.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from .core import (
    BLOCKING_RULES,
    DECLARED_RELEASES,
    REPO_ROOT,
    RULES,
    DeclaredRelease,
    Finding,
    RegenerationRefused,
    SourcesRefused,
    declared_release,
    regenerate,
    regenerate_command,
    verify,
)


def _selected(
    names: Sequence[str], parser: argparse.ArgumentParser
) -> list[DeclaredRelease]:
    if not names:
        return list(DECLARED_RELEASES)
    selected = []
    for name in names:
        try:
            selected.append(declared_release(name))
        except KeyError:
            known = ", ".join(declared.name for declared in DECLARED_RELEASES)
            parser.error(f"no declared release is named {name!r}; declared: {known}")
    return selected


#: What a contributor does about a finding regeneration will not repair.
_BLOCKED_BY = {
    "generated-release-unexpected-entry": "move or remove what the platform did not write",
    "generated-release-staging-left": "remove the staging directory",
    "generated-release-sources-refused": "fix the declared sources",
}


def _report(findings: Sequence[Finding]) -> None:
    statements = {rule.rule_id: rule.statement for rule in RULES}
    for finding in findings:
        print(f"DRIFTED  {finding.release}  {finding.rule_id}")
        print(f"         {finding.subject}: {finding.detail}")
        print(f"         {statements[finding.rule_id]}")
        for line in finding.diff:
            print(f"         {line}")


def _list() -> int:
    for declared in DECLARED_RELEASES:
        print(declared.name)
        print(f"  directory                   {declared.directory}")
        print(f"  contract                    {declared.contract}")
        for path in declared.bindings:
            print(f"  binding                     {path}")
        print(f"  binding name                {declared.binding_name or '(selected)'}")
        print(f"  platform defaults           {declared.platform_defaults} (api)")
        print(f"  platform-defaults revision  {declared.platform_defaults_revision}")
        print(f"  renderer revision           {declared.renderer_revision}")
    return 0


def _check(selected: Sequence[DeclaredRelease], root: Path) -> int:
    drifted = 0
    for declared in selected:
        findings = verify(declared, root)
        if not findings:
            print(
                f"OK       {declared.name}: both files are what the declared sources derive"
            )
            continue
        drifted += 1
        _report(findings)
        blocking = [f for f in findings if f.rule_id in BLOCKING_RULES]
        if blocking:
            print("         regeneration refuses this release until each is resolved:")
            for finding in blocking:
                print(f"           {_BLOCKED_BY[finding.rule_id]}: {finding.subject}")
        else:
            print(f"         regenerate with: {regenerate_command(declared)}")
            print("         read the diff first: regeneration replaces a hand edit")
    if drifted:
        print(f"{drifted} of {len(selected)} declared releases drifted")
        return 1
    return 0


def _write(selected: Sequence[DeclaredRelease], root: Path) -> int:
    status = 0
    for declared in selected:
        try:
            written = regenerate(declared, root)
        except SourcesRefused as refused:
            print(f"REFUSED  {declared.name}: nothing was written: {refused.reason}")
            status = 1
            continue
        except RegenerationRefused as refused:
            print(f"REFUSED  {declared.name}: nothing was written")
            for finding in refused.findings:
                print(
                    f"         {finding.rule_id}  {finding.subject}: {finding.detail}"
                )
            status = 1
            continue
        except OSError as error:
            print(f"FAILED   {declared.name}: {type(error).__name__}: {error}")
            print(
                "         the release directory may be absent; run --write again, "
                "or restore it from Git"
            )
            status = 1
            continue
        if written:
            print(f"WROTE    {declared.directory}")
        else:
            print(f"UNCHANGED {declared.directory}")
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tools.generated_release",
        description=(
            "Compare each committed generated release with what its declared "
            "sources derive, or regenerate a named release."
        ),
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--list",
        action="store_true",
        help="print every declared release and its inputs",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="compare the committed releases with what their sources derive",
    )
    group.add_argument(
        "--write",
        action="store_true",
        help="regenerate the named releases in place",
    )
    parser.add_argument("names", nargs="*", metavar="NAME", help="a declared release")
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="the repository copy to read and write (default: this checkout)",
    )
    arguments = parser.parse_args(argv)

    if arguments.list:
        if arguments.names:
            parser.error("--list takes no release name")
        return _list()
    if arguments.write and not arguments.names:
        parser.error("--write regenerates only the releases it is given by name")
    selected = _selected(arguments.names, parser)
    if arguments.check:
        return _check(selected, arguments.root)
    return _write(selected, arguments.root)


if __name__ == "__main__":  # pragma: no cover - exercised as a subprocess
    sys.exit(main())
